config/routes.rb
MigrateToPg240120140904::Application.routes.draw do
  get "for_pg/index"
  resources :pg_firsts

  

end

app/models/pg_first.rb
class PgFirst < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/for_pg_controller.rb
class ForPgController < ApplicationController
  def index
  end
end

app/controllers/pg_firsts_controller.rb
class PgFirstsController < ApplicationController
  before_action :set_pg_first, only: [:show, :edit, :update, :destroy]

  # GET /pg_firsts
  # GET /pg_firsts.json
  def index
    @pg_firsts = PgFirst.all
  end

  # GET /pg_firsts/1
  # GET /pg_firsts/1.json
  def show
  end

  # GET /pg_firsts/new
  def new
    @pg_first = PgFirst.new
  end

  # GET /pg_firsts/1/edit
  def edit
  end

  # POST /pg_firsts
  # POST /pg_firsts.json
  def create
    @pg_first = PgFirst.new(pg_first_params)

    respond_to do |format|
      if @pg_first.save
        format.html { redirect_to @pg_first, notice: 'Pg first was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pg_first }
      else
        format.html { render action: 'new' }
        format.json { render json: @pg_first.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pg_firsts/1
  # PATCH/PUT /pg_firsts/1.json
  def update
    respond_to do |format|
      if @pg_first.update(pg_first_params)
        format.html { redirect_to @pg_first, notice: 'Pg first was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pg_first.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pg_firsts/1
  # DELETE /pg_firsts/1.json
  def destroy
    @pg_first.destroy
    respond_to do |format|
      format.html { redirect_to pg_firsts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pg_first
      @pg_first = PgFirst.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pg_first_params
      params.require(:pg_first).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/for_pg_helper.rb
module ForPgHelper
end

app/helpers/pg_firsts_helper.rb
module PgFirstsHelper
end

app/views/for_pg/index.html.erb
<h1>ForPg#index</h1>
<p>Find me in app/views/for_pg/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MigrateToPg240120140904</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pg_firsts/_form.html.erb
<%= form_for(@pg_first) do |f| %>
  <% if @pg_first.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pg_first.errors.count, "error") %> prohibited this pg_first from being saved:</h2>

      <ul>
      <% @pg_first.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pg_firsts/edit.html.erb
<h1>Editing pg_first</h1>

<%= render 'form' %>

<%= link_to 'Show', @pg_first %> |
<%= link_to 'Back', pg_firsts_path %>

app/views/pg_firsts/index.html.erb
<h1>Listing pg_firsts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pg_firsts.each do |pg_first| %>
      <tr>
        <td><%= pg_first.name %></td>
        <td><%= link_to 'Show', pg_first %></td>
        <td><%= link_to 'Edit', edit_pg_first_path(pg_first) %></td>
        <td><%= link_to 'Destroy', pg_first, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pg first', new_pg_first_path %>

app/views/pg_firsts/new.html.erb
<h1>New pg_first</h1>

<%= render 'form' %>

<%= link_to 'Back', pg_firsts_path %>

app/views/pg_firsts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pg_first.name %>
</p>

<%= link_to 'Edit', edit_pg_first_path(@pg_first) %> |
<%= link_to 'Back', pg_firsts_path %>